Search.appendIndex(
    [
                {
            "fqsen": "\\Application\\Application",
            "name": "Application",
            "summary": "",
            "url": "classes/Application-Application.html"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetRequiredPhpVersion\u0028\u0029",
            "name": "GetRequiredPhpVersion",
            "summary": "Returns\u0020required\u0020PHP\u0020version",
            "url": "classes/Application-Application.html#method_GetRequiredPhpVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetName\u0028\u0029",
            "name": "GetName",
            "summary": "Returns\u0020a\u0020name\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetName"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetDescription\u0028\u0029",
            "name": "GetDescription",
            "summary": "Returns\u0020a\u0020description\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetDescription"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetAuthor\u0028\u0029",
            "name": "GetAuthor",
            "summary": "Returns\u0020an\u0020author\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetAuthor"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetVersion\u0028\u0029",
            "name": "GetVersion",
            "summary": "Returns\u0020a\u0020version\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetExecutableFileName\u0028\u0029",
            "name": "GetExecutableFileName",
            "summary": "Returns\u0020a\u0020full\u0020path\u0020to\u0020executable\u0020file",
            "url": "classes/Application-Application.html#method_GetExecutableFileName"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetExecutableDirectory\u0028\u0029",
            "name": "GetExecutableDirectory",
            "summary": "Returns\u0020a\u0020full\u0020path\u0020to\u0020work\u0020directory",
            "url": "classes/Application-Application.html#method_GetExecutableDirectory"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetFrameworkVersion\u0028\u0029",
            "name": "GetFrameworkVersion",
            "summary": "Returns\u0020a\u0020xRefCore\u0020version",
            "url": "classes/Application-Application.html#method_GetFrameworkVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003ASetTitle\u0028\u0029",
            "name": "SetTitle",
            "summary": "Sets\u0020title\u0020of\u0020process\u0020\u0028In\u0020Windows\u0020\u002D\u0020title\u0020of\u0020window\u0029",
            "url": "classes/Application-Application.html#method_SetTitle"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetUsername\u0028\u0029",
            "name": "GetUsername",
            "summary": "Returns\u0020a\u0020current\u0020username",
            "url": "classes/Application-Application.html#method_GetUsername"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetHomeDirectory\u0028\u0029",
            "name": "GetHomeDirectory",
            "summary": "Returns\u0020a\u0020home\u0020directory\u0020of\u0020current\u0020user\u0020\u0028in\u0020Windows\u0020is\u0020C\u003A\\Users\\your_username,\u0020in\u0020\u002Aunix\u0020systems\u0020is\u0020\/home\/your_username\u0020or\u0020\/root\u0029",
            "url": "classes/Application-Application.html#method_GetHomeDirectory"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AAmIRunningAsSuperuser\u0028\u0029",
            "name": "AmIRunningAsSuperuser",
            "summary": "Returns\u0020TRUE\u0020if\u0020your\u0020application\u0020started\u0020with\u0020Administrator\u0027s\u0020permissions.",
            "url": "classes/Application-Application.html#method_AmIRunningAsSuperuser"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AParseArguments\u0028\u0029",
            "name": "ParseArguments",
            "summary": "Parses\u0020arguments\u0020to\u0020values\u0020with\u0020keys,\u0020free\u002Dkey\u0020values\u0020and\u0020uninitialized\u0020keys",
            "url": "classes/Application-Application.html#method_ParseArguments"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\InvalidArgumentsPassed",
            "name": "InvalidArgumentsPassed",
            "summary": "Class\u0020InvalidArgumentsPassed",
            "url": "classes/CliForms-Exceptions-InvalidArgumentsPassed.html"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\InvalidHeaderTypeException",
            "name": "InvalidHeaderTypeException",
            "summary": "Class\u0020InvalidHeaderTypeException",
            "url": "classes/CliForms-Exceptions-InvalidHeaderTypeException.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox",
            "name": "ListBox",
            "summary": "Creates\u0020customized\u0020lists",
            "url": "classes/CliForms-ListBox-ListBox.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Creates\u0020new\u0020ListBox\u0020control",
            "url": "classes/CliForms-ListBox-ListBox.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003AClearItems\u0028\u0029",
            "name": "ClearItems",
            "summary": "Clears\u0020items",
            "url": "classes/CliForms-ListBox-ListBox.html#method_ClearItems"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetTitleColor\u0028\u0029",
            "name": "SetTitleColor",
            "summary": "Set\u0020color\u0020of\u0020title.\u0020Use\u0020ForegroundColors\u0020and\u0020BackgroundColors\u0020enums",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetTitleColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetDefaultItemStyle\u0028\u0029",
            "name": "SetDefaultItemStyle",
            "summary": "Sets\u0020default\u0020style\u0020for\u0020all\u0020items.\u0020You\u0020can\u0020set\u0020custom\u0020style\u0020for\u0020any\u0020title",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetDefaultItemStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowsHeaderType\u0028\u0029",
            "name": "SetRowsHeaderType",
            "summary": "Sets\u0020header\u0020type\u0020for\u0020items",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowsHeaderType"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowHeaderItemDelimiter\u0028\u0029",
            "name": "SetRowHeaderItemDelimiter",
            "summary": "Sets\u0020delimiter\u0020between\u0020header\u0020and\u0020item\u0020\u0028for\u0020example\u003A\u0020\u0022.\u0020\u0022\u0029",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowHeaderItemDelimiter"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowHeaderItemDelimiterStyle\u0028\u0029",
            "name": "SetRowHeaderItemDelimiterStyle",
            "summary": "Sets\u0020style\u0020for\u0020delimiter\u0020between\u0020header\u0020and\u0020item",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowHeaderItemDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003AAddItem\u0028\u0029",
            "name": "AddItem",
            "summary": "Addes\u0020item\u0020to\u0020ListBox\u0020collection",
            "url": "classes/CliForms-ListBox-ListBox.html#method_AddItem"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A_renderTitle\u0028\u0029",
            "name": "_renderTitle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method__renderTitle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A_renderBody\u0028\u0029",
            "name": "_renderBody",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method__renderBody"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ARender\u0028\u0029",
            "name": "Render",
            "summary": "Builds\u0020and\u0020renders\u0020list",
            "url": "classes/CliForms-ListBox-ListBox.html#method_Render"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_title"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024titleForegroundColor",
            "name": "titleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_titleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemForegroundColor",
            "name": "defaultItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemHeaderForegroundColor",
            "name": "defaultItemHeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemHeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterForegroundColor",
            "name": "defaultRowHeaderItemDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultRowHeaderItemDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024titleBackgroundColor",
            "name": "titleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_titleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemBackgroundColor",
            "name": "defaultItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemHeaderBackgroundColor",
            "name": "defaultItemHeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemHeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterBackgroundColor",
            "name": "defaultRowHeaderItemDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultRowHeaderItemDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024rowsHeaderType",
            "name": "rowsHeaderType",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_rowsHeaderType"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024rowHeaderItemDelimiter",
            "name": "rowHeaderItemDelimiter",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_rowHeaderItemDelimiter"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_items"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem",
            "name": "ListBoxItem",
            "summary": "ListBoxItem",
            "url": "classes/CliForms-ListBox-ListBoxItem.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetName\u0028\u0029",
            "name": "SetName",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetName"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetItemStyle\u0028\u0029",
            "name": "SetItemStyle",
            "summary": "Set\u0020style\u0020for\u0020item",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetItemStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetHeaderStyle\u0028\u0029",
            "name": "SetHeaderStyle",
            "summary": "Set\u0020header\u0020style",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetHeaderStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetDelimiterStyle\u0028\u0029",
            "name": "SetDelimiterStyle",
            "summary": "Set\u0020style\u0020for\u0020delimiter\u0020between\u0020header\u0020and\u0020item",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_Name"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024ItemForegroundColor",
            "name": "ItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_ItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024HeaderForegroundColor",
            "name": "HeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_HeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024DelimiterForegroundColor",
            "name": "DelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_DelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024ItemBackgroundColor",
            "name": "ItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_ItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024HeaderBackgroundColor",
            "name": "HeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_HeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024DelimiterBackgroundColor",
            "name": "DelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_DelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox",
            "name": "MenuBox",
            "summary": "Creates\u0020customized\u0020menu",
            "url": "classes/CliForms-MenuBox-MenuBox.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MenuBox\u0020constructor.",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AAddItem\u0028\u0029",
            "name": "AddItem",
            "summary": "Add\u0020item\u0020to\u0020collection",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_AddItem"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetZeroItem\u0028\u0029",
            "name": "SetZeroItem",
            "summary": "Sets\u0020zero\u0020item\u0020to\u0020your\u0020menu",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetZeroItem"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AClose\u0028\u0029",
            "name": "Close",
            "summary": "Closes\u0020menu",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Close"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AIsClosed\u0028\u0029",
            "name": "IsClosed",
            "summary": "Returns\u0020TRUE\u0020if\u0020menu\u0020closed",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_IsClosed"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetClearWindowOnRender\u0028\u0029",
            "name": "SetClearWindowOnRender",
            "summary": "Menu\u0020will\u0020be\u0020cleared\u0020after\u0020every\u0020render.\u0020Always\u0020TRUE\u0020if\u0020type\u0020of\u0020MenuBox\u0020is\u0020KeyPressType",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetClearWindowOnRender"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AGetThis\u0028\u0029",
            "name": "GetThis",
            "summary": "Returns\u0020your\u0020object\u0020which\u0020you\u0020passed\u0020in\u0020constructor",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_GetThis"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AResultOutput\u0028\u0029",
            "name": "ResultOutput",
            "summary": "Prints\u0020callback\u0020output\u0020of\u0020selected\u0020and\u0020called\u0020MenuBoxItem.\u0020It\u0027s\u0020recommended\u0020to\u0020use\u0020instead\u0020of\u0020Console\u003A\u003AWrite,\u0020because\u0020this\u0020method\u0020saves\u0020output\u0020after\u0020selecting\u0020another\u0020item.",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_ResultOutput"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AResultOutputLine\u0028\u0029",
            "name": "ResultOutputLine",
            "summary": "Prints\u0020callback\u0020output\u0020of\u0020selected\u0020and\u0020called\u0020MenuBoxItem\u0020and\u0020moves\u0020caret\u0020to\u0020new\u0020line.\u0020It\u0027s\u0020recommended\u0020to\u0020use\u0020instead\u0020of\u0020Console\u003A\u003AWriteLine,\u0020because\u0020this\u0020method\u0020saves\u0020output\u0020after\u0020selecting\u0020another\u0020item.",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_ResultOutputLine"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitle\u0028\u0029",
            "name": "SetInputTitle",
            "summary": "Sets\u0020title\u0020for\u0020read\u0020line\u0020input",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitleStyle\u0028\u0029",
            "name": "SetInputTitleStyle",
            "summary": "Sets\u0020style\u0020for\u0020read\u0020line\u0020title",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitleStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitleDelimiterStyle\u0028\u0029",
            "name": "SetInputTitleDelimiterStyle",
            "summary": "Sets\u0020style\u0020for\u0020delimiter\u0020of\u0020read\u0020line",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitleDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetDescription\u0028\u0029",
            "name": "SetDescription",
            "summary": "Sets\u0020description\u0020for\u0020your\u0020menu,\u0020which\u0020will\u0020be\u0020displayed\u0020between\u0020title\u0020and\u0020items",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetDescription"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetDescriptionStyle\u0028\u0029",
            "name": "SetDescriptionStyle",
            "summary": "Sets\u0020style\u0020for\u0020description",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetDescriptionStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetWrongItemTitle\u0028\u0029",
            "name": "SetWrongItemTitle",
            "summary": "Sets\u0020title\u0020which\u0020will\u0020be\u0020displayed\u0020if\u0020user\u0020selects\u0020a\u0020non\u002Dexists\u0020item",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetWrongItemTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetWrongItemTitleStyle\u0028\u0029",
            "name": "SetWrongItemTitleStyle",
            "summary": "Sets\u0020style\u0020for\u0020a\u0020non\u002Dexists\u0020item\u0020title",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetWrongItemTitleStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetSelectedItemStyle\u0028\u0029",
            "name": "SetSelectedItemStyle",
            "summary": "Sets\u0020style\u0020for\u0020selected\u0020item",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetSelectedItemStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ARender\u0028\u0029",
            "name": "Render",
            "summary": "Builds\u0020and\u0020renders\u0020your\u0020menu\u0020and\u0020runs\u0020read\u002Dline\u0020to\u0020select\u0020menu\u0020item",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Render"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ARender2\u0028\u0029",
            "name": "Render2",
            "summary": "Builds\u0020and\u0020renders\u0020your\u0020menu\u0020and\u0020runs\u0020read\u002Dline\u0020to\u0020select\u0020menu\u0020item\u0020and\u0020returns\u0020callback",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Render2"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024titleForegroundColor",
            "name": "titleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_titleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemForegroundColor",
            "name": "defaultItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemHeaderForegroundColor",
            "name": "defaultItemHeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemHeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterForegroundColor",
            "name": "defaultRowHeaderItemDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultRowHeaderItemDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleForegroundColor",
            "name": "inputTitleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleDelimiterForegroundColor",
            "name": "inputTitleDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024wrongItemTitleForegroundColor",
            "name": "wrongItemTitleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_wrongItemTitleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemHeaderForegroundColor",
            "name": "selectedItemHeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemHeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemDelimiterForegroundColor",
            "name": "selectedItemDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemRowForegroundColor",
            "name": "selectedItemRowForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemRowForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024titleBackgroundColor",
            "name": "titleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_titleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemBackgroundColor",
            "name": "defaultItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemHeaderBackgroundColor",
            "name": "defaultItemHeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemHeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterBackgroundColor",
            "name": "defaultRowHeaderItemDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultRowHeaderItemDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleBackgroundColor",
            "name": "inputTitleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleDelimiterBackgroundColor",
            "name": "inputTitleDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024wrongItemTitleBackgroundColor",
            "name": "wrongItemTitleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_wrongItemTitleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemHeaderBackgroundColor",
            "name": "selectedItemHeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemHeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemDelimiterBackgroundColor",
            "name": "selectedItemDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024selectedItemRowBackgroundColor",
            "name": "selectedItemRowBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_selectedItemRowBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_items"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem",
            "name": "MenuBoxItem",
            "summary": "MenuBoxItem",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MenuBoxItem\u0020constructor.",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003ASetOnSelect\u0028\u0029",
            "name": "SetOnSelect",
            "summary": "Sets\u0020callback\u0020when\u0020item\u0020selected",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method_SetOnSelect"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003ACallOnSelect\u0028\u0029",
            "name": "CallOnSelect",
            "summary": "Calls\u0020item\u0020callback",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method_CallOnSelect"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType",
            "name": "RowHeaderType",
            "summary": "Types\u0020of\u0020item\u0020headers",
            "url": "classes/CliForms-RowHeaderType.html"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ANUMERIC",
            "name": "NUMERIC",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_NUMERIC"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ASTARS",
            "name": "STARS",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_STARS"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ADOT1",
            "name": "DOT1",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_DOT1"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ADOT2",
            "name": "DOT2",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_DOT2"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW1",
            "name": "ARROW1",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW1"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW2",
            "name": "ARROW2",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW2"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW3",
            "name": "ARROW3",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW3"
        },                {
            "fqsen": "\\Data\\Enum",
            "name": "Enum",
            "summary": "Creating\u0020Enum\u0020objects",
            "url": "classes/Data-Enum.html"
        },                {
            "fqsen": "\\Data\\Enum\u003A\u003AGetValues\u0028\u0029",
            "name": "GetValues",
            "summary": "Get\u0020all\u0020values\u0020of\u0020Enum",
            "url": "classes/Data-Enum.html#method_GetValues"
        },                {
            "fqsen": "\\Data\\Enum\u003A\u003AHasItem\u0028\u0029",
            "name": "HasItem",
            "summary": "Returns\u0020TRUE\u0020if\u0020Enum\u0020contains\u0020specified\u0020item",
            "url": "classes/Data-Enum.html#method_HasItem"
        },                {
            "fqsen": "\\Data\\Exceptions\\CreateEnumInstanceException",
            "name": "CreateEnumInstanceException",
            "summary": "Class\u0020CreateEnumInstanceException",
            "url": "classes/Data-Exceptions-CreateEnumInstanceException.html"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors",
            "name": "BackgroundColors",
            "summary": "Contains\u0020background\u0020color\u0020codes\u0020for\u0020CLI",
            "url": "classes/Data-String-BackgroundColors.html"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AAUTO",
            "name": "AUTO",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_AUTO"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ABLACK",
            "name": "BLACK",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_BLACK"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ARED",
            "name": "RED",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_RED"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AGREEN",
            "name": "GREEN",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_GREEN"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AYELLOW",
            "name": "YELLOW",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_YELLOW"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ABLUE",
            "name": "BLUE",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_BLUE"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AMAGENTA",
            "name": "MAGENTA",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_MAGENTA"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ACYAN",
            "name": "CYAN",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_CYAN"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ALIGHT_GRAY",
            "name": "LIGHT_GRAY",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_LIGHT_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ColoredString",
            "name": "ColoredString",
            "summary": "Makes\u0020your\u0020string\u0020colored",
            "url": "classes/Data-String-ColoredString.html"
        },                {
            "fqsen": "\\Data\\String\\ColoredString\u003A\u003AGet\u0028\u0029",
            "name": "Get",
            "summary": "",
            "url": "classes/Data-String-ColoredString.html#method_Get"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors",
            "name": "ForegroundColors",
            "summary": "Contains\u0020foreground\u0020color\u0020codes\u0020for\u0020CLI",
            "url": "classes/Data-String-ForegroundColors.html"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AAUTO",
            "name": "AUTO",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_AUTO"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABLACK",
            "name": "BLACK",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BLACK"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_GRAY",
            "name": "DARK_GRAY",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_BLUE",
            "name": "DARK_BLUE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_BLUE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABLUE",
            "name": "BLUE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BLUE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_GREEN",
            "name": "DARK_GREEN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_GREEN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AGREEN",
            "name": "GREEN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_GREEN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_CYAN",
            "name": "DARK_CYAN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_CYAN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ACYAN",
            "name": "CYAN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_CYAN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_RED",
            "name": "DARK_RED",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_RED"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ARED",
            "name": "RED",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_RED"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_PURPLE",
            "name": "DARK_PURPLE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_PURPLE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003APURPLE",
            "name": "PURPLE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_PURPLE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABROWN",
            "name": "BROWN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BROWN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AYELLOW",
            "name": "YELLOW",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_YELLOW"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AGRAY",
            "name": "GRAY",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AWHITE",
            "name": "WHITE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_WHITE"
        },                {
            "fqsen": "\\IO\\Console",
            "name": "Console",
            "summary": "Console\u0020tools",
            "url": "classes/IO-Console.html"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AReadLine\u0028\u0029",
            "name": "ReadLine",
            "summary": "Reads\u0020line\u0020from\u0020default\u0020input\u0020stream.\u0020Attention\u0021\u0020In\u0020child\u002Dthreads\u0020this\u0020method\u0020works\u0020only\u0020in\u0020Windows\u0020but\u0020doesn\u0027t\u0020work\u0020in\u0020\u002AUnix\u0020systems",
            "url": "classes/IO-Console.html#method_ReadLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AReadKey\u0028\u0029",
            "name": "ReadKey",
            "summary": "Reads\u0020pressed\u0020key\u0020in\u0020input\u0020stream",
            "url": "classes/IO-Console.html#method_ReadKey"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AWriteLine\u0028\u0029",
            "name": "WriteLine",
            "summary": "Writes\u0020text\u0020to\u0020default\u0020stream\u0020output\u0020and\u0020sets\u0020pointer\u0020to\u0020new\u0020line",
            "url": "classes/IO-Console.html#method_WriteLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AWrite\u0028\u0029",
            "name": "Write",
            "summary": "Writes\u0020text\u0020to\u0020default\u0020stream\u0020output",
            "url": "classes/IO-Console.html#method_Write"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AClearLine\u0028\u0029",
            "name": "ClearLine",
            "summary": "Clears\u0020a\u0020line",
            "url": "classes/IO-Console.html#method_ClearLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AClearWindow\u0028\u0029",
            "name": "ClearWindow",
            "summary": "Clears\u0020all\u0020output\u0020in\u0020window",
            "url": "classes/IO-Console.html#method_ClearWindow"
        },                {
            "fqsen": "\\IO\\FileDirectory",
            "name": "FileDirectory",
            "summary": "File\u0020system\u0020tools",
            "url": "classes/IO-FileDirectory.html"
        },                {
            "fqsen": "\\IO\\FileDirectory\u003A\u003ACopy\u0028\u0029",
            "name": "Copy",
            "summary": "Copies\u0020file\u0020or\u0020folders\u0020to\u0020target\u0020directory",
            "url": "classes/IO-FileDirectory.html#method_Copy"
        },                {
            "fqsen": "\\IO\\FileDirectory\u003A\u003ADelete\u0028\u0029",
            "name": "Delete",
            "summary": "Deletes\u0020file\u0020or\u0020directory\u0020\u0028even\u0020if\u0020directory\u0020is\u0020not\u0020empty\u0029",
            "url": "classes/IO-FileDirectory.html#method_Delete"
        },                {
            "fqsen": "\\Threading\\ChildThreadedObject",
            "name": "ChildThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020all\u0020methods\u0020and\u0020properties\u0020in\u0020child\u0020threaded\u0020class",
            "url": "classes/Threading-ChildThreadedObject.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\AbstractClassThreadException",
            "name": "AbstractClassThreadException",
            "summary": "Class\u0020AbstractClassThreadException",
            "url": "classes/Threading-Exceptions-AbstractClassThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\AccessToClosedThreadException",
            "name": "AccessToClosedThreadException",
            "summary": "Class\u0020AccessToClosedThreadException",
            "url": "classes/Threading-Exceptions-AccessToClosedThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\BadDataAccessException",
            "name": "BadDataAccessException",
            "summary": "Class\u0020BadDataAccessException",
            "url": "classes/Threading-Exceptions-BadDataAccessException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\BadMethodCallException",
            "name": "BadMethodCallException",
            "summary": "Class\u0020BadMethodCallException",
            "url": "classes/Threading-Exceptions-BadMethodCallException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\ClassNotFoundException",
            "name": "ClassNotFoundException",
            "summary": "Class\u0020ClassNotFoundException",
            "url": "classes/Threading-Exceptions-ClassNotFoundException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\InvalidArgumentsPassedException",
            "name": "InvalidArgumentsPassedException",
            "summary": "Class\u0020InvalidArgumentsPassedException",
            "url": "classes/Threading-Exceptions-InvalidArgumentsPassedException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\InvalidResultReceivedException",
            "name": "InvalidResultReceivedException",
            "summary": "Class\u0020InvalidResultReceivedException",
            "url": "classes/Threading-Exceptions-InvalidResultReceivedException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\NewThreadException",
            "name": "NewThreadException",
            "summary": "Class\u0020NewThreadException",
            "url": "classes/Threading-Exceptions-NewThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SystemMethodCallException",
            "name": "SystemMethodCallException",
            "summary": "Class\u0020SystemMethodCallException",
            "url": "classes/Threading-Exceptions-SystemMethodCallException.html"
        },                {
            "fqsen": "\\Threading\\ParentThreadedObject",
            "name": "ParentThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020all\u0020methods\u0020and\u0020properties\u0020in\u0020parent\u0020threaded\u0020object",
            "url": "classes/Threading-ParentThreadedObject.html"
        },                {
            "fqsen": "\\Threading\\Thread",
            "name": "Thread",
            "summary": "Allows\u0020you\u0020to\u0020create\u0020new\u0020threads.\u0020At\u0020the\u0020same\u0020time,\u0020this\u0020class\u0020is\u0020used\u0020by\u0020the\u0020child\u0020thread\u0020to\u0020access\u0020the\u0020parent",
            "url": "classes/Threading-Thread.html"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AThreaded\u0028\u0029",
            "name": "Threaded",
            "summary": "This\u0020method\u0020calls\u0020automatically\u0020in\u0020child\u002Dthread\u0020when\u0020it\u0020was\u0020created",
            "url": "classes/Threading-Thread.html#method_Threaded"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetAllChildThreads\u0028\u0029",
            "name": "GetAllChildThreads",
            "summary": "Returns\u0020all\u0020child\u0020threads",
            "url": "classes/Threading-Thread.html#method_GetAllChildThreads"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetParentThreadPid\u0028\u0029",
            "name": "GetParentThreadPid",
            "summary": "Returns\u0020a\u0020PID\u0020of\u0020parent\u0020thread",
            "url": "classes/Threading-Thread.html#method_GetParentThreadPid"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetParentThreadPort\u0028\u0029",
            "name": "GetParentThreadPort",
            "summary": "Returns\u0020a\u0020port\u0020of\u0020parent\u0020thread",
            "url": "classes/Threading-Thread.html#method_GetParentThreadPort"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AIsParentStillRunning\u0028\u0029",
            "name": "IsParentStillRunning",
            "summary": "Returns\u0020TRUE\u0020if\u0020parent\u0020thread\u0020still\u0020running",
            "url": "classes/Threading-Thread.html#method_IsParentStillRunning"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AIsWindows\u0028\u0029",
            "name": "IsWindows",
            "summary": "",
            "url": "classes/Threading-Thread.html#method_IsWindows"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetParentThreadedObject\u0028\u0029",
            "name": "GetParentThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020public\u0020methods\u0020and\u0020properties\u0020of\u0020threaded\u0020parent\u0020object",
            "url": "classes/Threading-Thread.html#method_GetParentThreadedObject"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AWaitForParentAccess\u0028\u0029",
            "name": "WaitForParentAccess",
            "summary": "Blocks\u0020child\u002Dthread\u0020and\u0020waits\u0020when\u0020parent\u002Dthread\u0020will\u0020join\u0020to\u0020child\u002Dthread",
            "url": "classes/Threading-Thread.html#method_WaitForParentAccess"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AFinishSychnorization\u0028\u0029",
            "name": "FinishSychnorization",
            "summary": "Unjoins\u0020and\u0020unblocks\u0020parent\u002Dthread.\u0020ATTENTION\u0021\u0020Until\u0020you\u0020call\u0020this\u0020method,\u0020the\u0020parent\u002Dthread\u0020will\u0020be\u0020frozen\u0021",
            "url": "classes/Threading-Thread.html#method_FinishSychnorization"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003ARun\u0028\u0029",
            "name": "Run",
            "summary": "Creates\u0020and\u0020starts\u0020a\u0020new\u0020thread\u0020of\u0020class",
            "url": "classes/Threading-Thread.html#method_Run"
        },                {
            "fqsen": "\\Threading\\Threaded",
            "name": "Threaded",
            "summary": "Provides\u0020information\u0020and\u0020access\u0020to\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetChildThreadedObject\u0028\u0029",
            "name": "GetChildThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020public\u0020methods\u0020and\u0020properties\u0020of\u0020threaded\u0020child\u0020class",
            "url": "classes/Threading-Threaded.html#method_GetChildThreadedObject"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetChildPid\u0028\u0029",
            "name": "GetChildPid",
            "summary": "Returns\u0020PID\u0020of\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_GetChildPid"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetChildPort\u0028\u0029",
            "name": "GetChildPort",
            "summary": "Returns\u0020port\u0020of\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_GetChildPort"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetArguments\u0028\u0029",
            "name": "GetArguments",
            "summary": "Returns\u0020list\u0020of\u0020arguments\u0020passed\u0020by\u0020the\u0020parent\u0020thread",
            "url": "classes/Threading-Threaded.html#method_GetArguments"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetClassName\u0028\u0029",
            "name": "GetClassName",
            "summary": "Returns\u0020name\u0020of\u0020threaded\u0020class",
            "url": "classes/Threading-Threaded.html#method_GetClassName"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AIsRunning\u0028\u0029",
            "name": "IsRunning",
            "summary": "Returns\u0020TRUE\u0020if\u0020child\u0020thread\u0020still\u0020running",
            "url": "classes/Threading-Threaded.html#method_IsRunning"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AWaitForChildAccess\u0028\u0029",
            "name": "WaitForChildAccess",
            "summary": "Waits\u0020for\u0020the\u0020child\u0020thread\u0020to\u0020begin\u0020interacting\u0020with\u0020the\u0020parent\u0020thread.\u0020The\u0020parent\u0020thread\u0020will\u0020be\u0020frozen\u0020and\u0020wait\u0020for\u0020the\u0020child\u0020thread\u0020to\u0020finish\u0020synchronizing",
            "url": "classes/Threading-Threaded.html#method_WaitForChildAccess"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AFinishSychnorization\u0028\u0029",
            "name": "FinishSychnorization",
            "summary": "Stop\u0020synchronization\u0020with\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_FinishSychnorization"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AKill\u0028\u0029",
            "name": "Kill",
            "summary": "Kills\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_Kill"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\ItemIsNotArrayException",
            "name": "ItemIsNotArrayException",
            "summary": "Class\u0020ItemIsNotArrayException",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-ItemIsNotArrayException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\ItemIsNotArrayException\u003A\u003A\u0024Key",
            "name": "Key",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-ItemIsNotArrayException.html#property_Key"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\ItemIsNotArrayException\u003A\u003A\u0024PassedKeys",
            "name": "PassedKeys",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-ItemIsNotArrayException.html#property_PassedKeys"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\ItemIsNotArrayException\u003A\u003A\u0024Type",
            "name": "Type",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-ItemIsNotArrayException.html#property_Type"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\KeyNotFoundException",
            "name": "KeyNotFoundException",
            "summary": "Class\u0020KeyNotFoundException",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-KeyNotFoundException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\KeyNotFoundException\u003A\u003A\u0024Key",
            "name": "Key",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-KeyNotFoundException.html#property_Key"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\KeyNotFoundException\u003A\u003A\u0024PassedKeys",
            "name": "PassedKeys",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-KeyNotFoundException.html#property_PassedKeys"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\UnknownErrorException",
            "name": "UnknownErrorException",
            "summary": "Class\u0020UnknownErrorException",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-UnknownErrorException.html"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray",
            "name": "SuperGlobalArray",
            "summary": "Provides\u0020access\u0020to\u0020super\u0020global\u0020threaded\u0020array.\u0020You\u0020can\u0020get\u0020this\u0020array\u0020from\u0020any\u0020thread",
            "url": "classes/Threading-SuperGlobalArray.html"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AGetInstance\u0028\u0029",
            "name": "GetInstance",
            "summary": "Returns\u0020instance\u0020of\u0020super\u0020global\u0020array",
            "url": "classes/Threading-SuperGlobalArray.html#method_GetInstance"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AGet\u0028\u0029",
            "name": "Get",
            "summary": "Returns\u0020value\u0020of\u0020array\u0020key",
            "url": "classes/Threading-SuperGlobalArray.html#method_Get"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003ASet\u0028\u0029",
            "name": "Set",
            "summary": "Sets\u0020new\u0020value\u0020for\u0020key",
            "url": "classes/Threading-SuperGlobalArray.html#method_Set"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AAdd\u0028\u0029",
            "name": "Add",
            "summary": "Addes\u0020value\u0020to\u0020array\u0020with\u0020numeric\u0020index",
            "url": "classes/Threading-SuperGlobalArray.html#method_Add"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AIsSet\u0028\u0029",
            "name": "IsSet",
            "summary": "Returns\u0020TRUE\u0020if\u0020item\u0020with\u0020same\u0020key\u0020exists",
            "url": "classes/Threading-SuperGlobalArray.html#method_IsSet"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AUnset\u0028\u0029",
            "name": "Unset",
            "summary": "Deletes\u0020item\u0020in\u0020array,\u0020like\u0020native\u0020PHP\u0020\u0060unset\u0028\u0029\u0060\u0020function",
            "url": "classes/Threading-SuperGlobalArray.html#method_Unset"
        },                {
            "fqsen": "\\Threading\\SuperGlobalArray\u003A\u003AOperator\u0028\u0029",
            "name": "Operator",
            "summary": "Executes\u0020operator\u0020with\u0020array\u0020item",
            "url": "classes/Threading-SuperGlobalArray.html#method_Operator"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidOperatorException",
            "name": "InvalidOperatorException",
            "summary": "Class\u0020InvalidOperatorException",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidOperatorException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidOperatorException\u003A\u003A\u0024Operator",
            "name": "Operator",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidOperatorException.html#property_Operator"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidOperatorException\u003A\u003A\u0024Operators",
            "name": "Operators",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidOperatorException.html#property_Operators"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidOperatorException\u003A\u003A\u0024Value",
            "name": "Value",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidOperatorException.html#property_Value"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException",
            "name": "InvalidValueTypeException",
            "summary": "Class\u0020InvalidValueTypeException",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException\u003A\u003A\u0024Operator",
            "name": "Operator",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html#property_Operator"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException\u003A\u003A\u0024Operators",
            "name": "Operators",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html#property_Operators"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException\u003A\u003A\u0024Value",
            "name": "Value",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html#property_Value"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException\u003A\u003A\u0024ExpectedTypes",
            "name": "ExpectedTypes",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html#property_ExpectedTypes"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray\\InvalidValueTypeException\u003A\u003A\u0024GivenType",
            "name": "GivenType",
            "summary": "",
            "url": "classes/Threading-Exceptions-SuperGlobalArray-InvalidValueTypeException.html#property_GivenType"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\InvalidMenuBoxTypeException",
            "name": "InvalidMenuBoxTypeException",
            "summary": "",
            "url": "classes/CliForms-Exceptions-InvalidMenuBoxTypeException.html"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\NoItemsAddedException",
            "name": "NoItemsAddedException",
            "summary": "Class\u0020NoItemsAddedException",
            "url": "classes/CliForms-Exceptions-NoItemsAddedException.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxTypes",
            "name": "MenuBoxTypes",
            "summary": "Creating\u0020Enum\u0020objects",
            "url": "classes/CliForms-MenuBox-MenuBoxTypes.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxTypes\u003A\u003AInputItemNumberType",
            "name": "InputItemNumberType",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxTypes.html#constant_InputItemNumberType"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxTypes\u003A\u003AKeyPressType",
            "name": "KeyPressType",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxTypes.html#constant_KeyPressType"
        },                {
            "fqsen": "\\Data\\String\\Bg",
            "name": "Bg",
            "summary": "Short\u0020aliases\u0020for\u0020BackgroundColors",
            "url": "classes/Data-String-Bg.html"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Aa",
            "name": "a",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_a"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Ab",
            "name": "b",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_b"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Ar",
            "name": "r",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_r"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Agr",
            "name": "gr",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_gr"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Ay",
            "name": "y",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_y"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Abl",
            "name": "bl",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_bl"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Am",
            "name": "m",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_m"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Ac",
            "name": "c",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_c"
        },                {
            "fqsen": "\\Data\\String\\Bg\u003A\u003Alg",
            "name": "lg",
            "summary": "",
            "url": "classes/Data-String-Bg.html#constant_lg"
        },                {
            "fqsen": "\\Data\\String\\Fg",
            "name": "Fg",
            "summary": "Short\u0020aliases\u0020for\u0020ForegroundColors",
            "url": "classes/Data-String-Fg.html"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Aa",
            "name": "a",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_a"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Ab",
            "name": "b",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_b"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adg",
            "name": "dg",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_dg"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adb",
            "name": "db",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_db"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Abl",
            "name": "bl",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_bl"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adgn",
            "name": "dgn",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_dgn"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Agn",
            "name": "gn",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_gn"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adc",
            "name": "dc",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_dc"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Ac",
            "name": "c",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_c"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adr",
            "name": "dr",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_dr"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Adp",
            "name": "dp",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_dp"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Ap",
            "name": "p",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_p"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Abr",
            "name": "br",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_br"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Ay",
            "name": "y",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_y"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Ag",
            "name": "g",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_g"
        },                {
            "fqsen": "\\Data\\String\\Fg\u003A\u003Aw",
            "name": "w",
            "summary": "",
            "url": "classes/Data-String-Fg.html#constant_w"
        },                {
            "fqsen": "\\HttpServer\\Exceptions\\ServerStartException",
            "name": "ServerStartException",
            "summary": "Class\u0020ServerStartException",
            "url": "classes/HttpServer-Exceptions-ServerStartException.html"
        },                {
            "fqsen": "\\HttpServer\\Request",
            "name": "Request",
            "summary": "Contains\u0020request\u0020data",
            "url": "classes/HttpServer-Request.html"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003AGetRawContent\u0028\u0029",
            "name": "GetRawContent",
            "summary": "Returns\u0020body\u0020of\u0020request",
            "url": "classes/HttpServer-Request.html#method_GetRawContent"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RequestMethod",
            "name": "RequestMethod",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RequestMethod"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RequestUri",
            "name": "RequestUri",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RequestUri"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024QueryString",
            "name": "QueryString",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_QueryString"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024PathInfo",
            "name": "PathInfo",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_PathInfo"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024ServerProtocol",
            "name": "ServerProtocol",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_ServerProtocol"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RemoteAddress",
            "name": "RemoteAddress",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RemoteAddress"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RequestTime",
            "name": "RequestTime",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RequestTime"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024ServerPort",
            "name": "ServerPort",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_ServerPort"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RemotePort",
            "name": "RemotePort",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RemotePort"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024MasterTime",
            "name": "MasterTime",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_MasterTime"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RequestTimeFloat",
            "name": "RequestTimeFloat",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RequestTimeFloat"
        },                {
            "fqsen": "\\HttpServer\\Request\u003A\u003A\u0024RequestError",
            "name": "RequestError",
            "summary": "",
            "url": "classes/HttpServer-Request.html#property_RequestError"
        },                {
            "fqsen": "\\HttpServer\\Response",
            "name": "Response",
            "summary": "Package\u0020contains\u0020method\u0020for\u0020response\u0020build",
            "url": "classes/HttpServer-Response.html"
        },                {
            "fqsen": "\\HttpServer\\Response\u003A\u003AHeader\u0028\u0029",
            "name": "Header",
            "summary": "Adds\u0020header\u0020for\u0020response",
            "url": "classes/HttpServer-Response.html#method_Header"
        },                {
            "fqsen": "\\HttpServer\\Response\u003A\u003AStatus\u0028\u0029",
            "name": "Status",
            "summary": "Sets\u0020HTTP\u002Dstatus",
            "url": "classes/HttpServer-Response.html#method_Status"
        },                {
            "fqsen": "\\HttpServer\\Response\u003A\u003AIsClosed\u0028\u0029",
            "name": "IsClosed",
            "summary": "Returns\u0020TRUE\u0020if\u0020connection\u0020closed",
            "url": "classes/HttpServer-Response.html#method_IsClosed"
        },                {
            "fqsen": "\\HttpServer\\Response\u003A\u003AEnd\u0028\u0029",
            "name": "End",
            "summary": "Sets\u0020response\u0020for\u0020client\u0020and\u0020closes\u0020connection",
            "url": "classes/HttpServer-Response.html#method_End"
        },                {
            "fqsen": "\\HttpServer\\Response\u003A\u003AGetFullResponse\u0028\u0029",
            "name": "GetFullResponse",
            "summary": "Returns\u0020full\u0020response\u0020with\u0020all\u0020headers",
            "url": "classes/HttpServer-Response.html#method_GetFullResponse"
        },                {
            "fqsen": "\\HttpServer\\Server",
            "name": "Server",
            "summary": "HTTP\u002Dserver",
            "url": "classes/HttpServer-Server.html"
        },                {
            "fqsen": "\\HttpServer\\Server\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Server\u0020constructor.",
            "url": "classes/HttpServer-Server.html#method___construct"
        },                {
            "fqsen": "\\HttpServer\\Server\u003A\u003AOn\u0028\u0029",
            "name": "On",
            "summary": "Add\u0020new\u0020event",
            "url": "classes/HttpServer-Server.html#method_On"
        },                {
            "fqsen": "\\HttpServer\\Server\u003A\u003AStart\u0028\u0029",
            "name": "Start",
            "summary": "Run\u0020server",
            "url": "classes/HttpServer-Server.html#method_Start"
        },                {
            "fqsen": "\\HttpServer\\Server\u003A\u003AShutdown\u0028\u0029",
            "name": "Shutdown",
            "summary": "Shutdown\u0020server",
            "url": "classes/HttpServer-Server.html#method_Shutdown"
        },                {
            "fqsen": "\\HttpServer\\Exceptions\\UnknownEventException",
            "name": "UnknownEventException",
            "summary": "",
            "url": "classes/HttpServer-Exceptions-UnknownEventException.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Application",
            "name": "Application",
            "summary": "",
            "url": "namespaces/application.html"
        },                {
            "fqsen": "\\CliForms\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/cliforms-exceptions.html"
        },                {
            "fqsen": "\\CliForms\\ListBox",
            "name": "ListBox",
            "summary": "",
            "url": "namespaces/cliforms-listbox.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox",
            "name": "MenuBox",
            "summary": "",
            "url": "namespaces/cliforms-menubox.html"
        },                {
            "fqsen": "\\CliForms",
            "name": "CliForms",
            "summary": "",
            "url": "namespaces/cliforms.html"
        },                {
            "fqsen": "\\Data",
            "name": "Data",
            "summary": "",
            "url": "namespaces/data.html"
        },                {
            "fqsen": "\\Data\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/data-exceptions.html"
        },                {
            "fqsen": "\\Data\\String",
            "name": "String",
            "summary": "",
            "url": "namespaces/data-string.html"
        },                {
            "fqsen": "\\HttpServer\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/httpserver-exceptions.html"
        },                {
            "fqsen": "\\HttpServer",
            "name": "HttpServer",
            "summary": "",
            "url": "namespaces/httpserver.html"
        },                {
            "fqsen": "\\IO",
            "name": "IO",
            "summary": "",
            "url": "namespaces/io.html"
        },                {
            "fqsen": "\\Threading",
            "name": "Threading",
            "summary": "",
            "url": "namespaces/threading.html"
        },                {
            "fqsen": "\\Threading\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/threading-exceptions.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SuperGlobalArray",
            "name": "SuperGlobalArray",
            "summary": "",
            "url": "namespaces/threading-exceptions-superglobalarray.html"
        }            ]
);
