Search.appendIndex(
    [
                {
            "fqsen": "\\Application\\Application",
            "name": "Application",
            "summary": "",
            "url": "classes/Application-Application.html"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetRequiredPhpVersion\u0028\u0029",
            "name": "GetRequiredPhpVersion",
            "summary": "Returns\u0020required\u0020PHP\u0020version",
            "url": "classes/Application-Application.html#method_GetRequiredPhpVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetName\u0028\u0029",
            "name": "GetName",
            "summary": "Returns\u0020a\u0020name\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetName"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetDescription\u0028\u0029",
            "name": "GetDescription",
            "summary": "Returns\u0020a\u0020description\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetDescription"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetAuthor\u0028\u0029",
            "name": "GetAuthor",
            "summary": "Returns\u0020an\u0020author\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetAuthor"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetVersion\u0028\u0029",
            "name": "GetVersion",
            "summary": "Returns\u0020a\u0020version\u0020of\u0020application",
            "url": "classes/Application-Application.html#method_GetVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetExecutableFileName\u0028\u0029",
            "name": "GetExecutableFileName",
            "summary": "Returns\u0020a\u0020full\u0020path\u0020to\u0020executable\u0020file",
            "url": "classes/Application-Application.html#method_GetExecutableFileName"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetExecutableDirectory\u0028\u0029",
            "name": "GetExecutableDirectory",
            "summary": "Returns\u0020a\u0020full\u0020path\u0020to\u0020work\u0020directory",
            "url": "classes/Application-Application.html#method_GetExecutableDirectory"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AGetFrameworkVersion\u0028\u0029",
            "name": "GetFrameworkVersion",
            "summary": "Returns\u0020a\u0020framework\u0020version",
            "url": "classes/Application-Application.html#method_GetFrameworkVersion"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003ASetTitle\u0028\u0029",
            "name": "SetTitle",
            "summary": "Sets\u0020title\u0020of\u0020process\u0020\u0028In\u0020Windows\u0020\u002D\u0020title\u0020of\u0020window\u0029",
            "url": "classes/Application-Application.html#method_SetTitle"
        },                {
            "fqsen": "\\Application\\Application\u003A\u003AParseArguments\u0028\u0029",
            "name": "ParseArguments",
            "summary": "Parses\u0020arguments\u0020to\u0020values\u0020with\u0020keys,\u0020free\u002Dkey\u0020values\u0020and\u0020uninitialized\u0020keys",
            "url": "classes/Application-Application.html#method_ParseArguments"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\InvalidArgumentsPassed",
            "name": "InvalidArgumentsPassed",
            "summary": "",
            "url": "classes/CliForms-Exceptions-InvalidArgumentsPassed.html"
        },                {
            "fqsen": "\\CliForms\\Exceptions\\InvalidHeaderTypeException",
            "name": "InvalidHeaderTypeException",
            "summary": "",
            "url": "classes/CliForms-Exceptions-InvalidHeaderTypeException.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox",
            "name": "ListBox",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003AClearItems\u0028\u0029",
            "name": "ClearItems",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_ClearItems"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetTitleColor\u0028\u0029",
            "name": "SetTitleColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetTitleColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetDefaultItemStyle\u0028\u0029",
            "name": "SetDefaultItemStyle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetDefaultItemStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowsHeaderType\u0028\u0029",
            "name": "SetRowsHeaderType",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowsHeaderType"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowHeaderItemDelimiter\u0028\u0029",
            "name": "SetRowHeaderItemDelimiter",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowHeaderItemDelimiter"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ASetRowHeaderItemDelimiterStyle\u0028\u0029",
            "name": "SetRowHeaderItemDelimiterStyle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_SetRowHeaderItemDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003AAddItem\u0028\u0029",
            "name": "AddItem",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_AddItem"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A_renderTitle\u0028\u0029",
            "name": "_renderTitle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method__renderTitle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A_renderBody\u0028\u0029",
            "name": "_renderBody",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method__renderBody"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003ARender\u0028\u0029",
            "name": "Render",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#method_Render"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024title",
            "name": "title",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_title"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024titleForegroundColor",
            "name": "titleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_titleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemForegroundColor",
            "name": "defaultItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemHeaderForegroundColor",
            "name": "defaultItemHeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemHeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterForegroundColor",
            "name": "defaultRowHeaderItemDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultRowHeaderItemDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024titleBackgroundColor",
            "name": "titleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_titleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemBackgroundColor",
            "name": "defaultItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultItemHeaderBackgroundColor",
            "name": "defaultItemHeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultItemHeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterBackgroundColor",
            "name": "defaultRowHeaderItemDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_defaultRowHeaderItemDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024rowsHeaderType",
            "name": "rowsHeaderType",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_rowsHeaderType"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024rowHeaderItemDelimiter",
            "name": "rowHeaderItemDelimiter",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_rowHeaderItemDelimiter"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBox\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBox.html#property_items"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem",
            "name": "ListBoxItem",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetName\u0028\u0029",
            "name": "SetName",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetName"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetItemStyle\u0028\u0029",
            "name": "SetItemStyle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetItemStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetHeaderStyle\u0028\u0029",
            "name": "SetHeaderStyle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetHeaderStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003ASetDelimiterStyle\u0028\u0029",
            "name": "SetDelimiterStyle",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#method_SetDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024Name",
            "name": "Name",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_Name"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024ItemForegroundColor",
            "name": "ItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_ItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024HeaderForegroundColor",
            "name": "HeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_HeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024DelimiterForegroundColor",
            "name": "DelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_DelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024ItemBackgroundColor",
            "name": "ItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_ItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024HeaderBackgroundColor",
            "name": "HeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_HeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\ListBox\\ListBoxItem\u003A\u003A\u0024DelimiterBackgroundColor",
            "name": "DelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-ListBox-ListBoxItem.html#property_DelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox",
            "name": "MenuBox",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AAddItem\u0028\u0029",
            "name": "AddItem",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_AddItem"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetZeroItem\u0028\u0029",
            "name": "SetZeroItem",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetZeroItem"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AClose\u0028\u0029",
            "name": "Close",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Close"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AIsClosed\u0028\u0029",
            "name": "IsClosed",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_IsClosed"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetClearWindowOnRender\u0028\u0029",
            "name": "SetClearWindowOnRender",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetClearWindowOnRender"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AGetThis\u0028\u0029",
            "name": "GetThis",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_GetThis"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitle\u0028\u0029",
            "name": "SetInputTitle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitleStyle\u0028\u0029",
            "name": "SetInputTitleStyle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitleStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetInputTitleDelimiterStyle\u0028\u0029",
            "name": "SetInputTitleDelimiterStyle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetInputTitleDelimiterStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetDescriptionStyle\u0028\u0029",
            "name": "SetDescriptionStyle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetDescriptionStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetDescription\u0028\u0029",
            "name": "SetDescription",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetDescription"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetWrongItemTitle\u0028\u0029",
            "name": "SetWrongItemTitle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetWrongItemTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ASetWrongItemTitleStyle\u0028\u0029",
            "name": "SetWrongItemTitleStyle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_SetWrongItemTitleStyle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A_renderBody\u0028\u0029",
            "name": "_renderBody",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method__renderBody"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003AGetEmptyFunction\u0028\u0029",
            "name": "GetEmptyFunction",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_GetEmptyFunction"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ARender\u0028\u0029",
            "name": "Render",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Render"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003ARender2\u0028\u0029",
            "name": "Render2",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#method_Render2"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024titleForegroundColor",
            "name": "titleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_titleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemForegroundColor",
            "name": "defaultItemForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemHeaderForegroundColor",
            "name": "defaultItemHeaderForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemHeaderForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterForegroundColor",
            "name": "defaultRowHeaderItemDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultRowHeaderItemDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleForegroundColor",
            "name": "inputTitleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleDelimiterForegroundColor",
            "name": "inputTitleDelimiterForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleDelimiterForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024wrongItemTitleForegroundColor",
            "name": "wrongItemTitleForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_wrongItemTitleForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024titleBackgroundColor",
            "name": "titleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_titleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemBackgroundColor",
            "name": "defaultItemBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultItemHeaderBackgroundColor",
            "name": "defaultItemHeaderBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultItemHeaderBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024defaultRowHeaderItemDelimiterBackgroundColor",
            "name": "defaultRowHeaderItemDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_defaultRowHeaderItemDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleBackgroundColor",
            "name": "inputTitleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitleDelimiterBackgroundColor",
            "name": "inputTitleDelimiterBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitleDelimiterBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024wrongItemTitleBackgroundColor",
            "name": "wrongItemTitleBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_wrongItemTitleBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024descriptionForegroundColor",
            "name": "descriptionForegroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_descriptionForegroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024descriptionBackgroundColor",
            "name": "descriptionBackgroundColor",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_descriptionBackgroundColor"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024inputTitle",
            "name": "inputTitle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_inputTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024wrongItemTitle",
            "name": "wrongItemTitle",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_wrongItemTitle"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024description",
            "name": "description",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_description"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024mythis",
            "name": "mythis",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_mythis"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024items",
            "name": "items",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_items"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024clearOnRender",
            "name": "clearOnRender",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_clearOnRender"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024closeMenu",
            "name": "closeMenu",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_closeMenu"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024render2wrongItemSelected",
            "name": "render2wrongItemSelected",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_render2wrongItemSelected"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024cleared",
            "name": "cleared",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_cleared"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBox\u003A\u003A\u0024zeroItem",
            "name": "zeroItem",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBox.html#property_zeroItem"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem",
            "name": "MenuBoxItem",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method___construct"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003ASetOnSelect\u0028\u0029",
            "name": "SetOnSelect",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method_SetOnSelect"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003ACallOnSelect\u0028\u0029",
            "name": "CallOnSelect",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method_CallOnSelect"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003AGetCallbackForRender2\u0028\u0029",
            "name": "GetCallbackForRender2",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#method_GetCallbackForRender2"
        },                {
            "fqsen": "\\CliForms\\MenuBox\\MenuBoxItem\u003A\u003A\u0024callback",
            "name": "callback",
            "summary": "",
            "url": "classes/CliForms-MenuBox-MenuBoxItem.html#property_callback"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType",
            "name": "RowHeaderType",
            "summary": "Creating\u0020Enum\u0020objects",
            "url": "classes/CliForms-RowHeaderType.html"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ANUMERIC",
            "name": "NUMERIC",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_NUMERIC"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ASTARS",
            "name": "STARS",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_STARS"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ADOT1",
            "name": "DOT1",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_DOT1"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003ADOT2",
            "name": "DOT2",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_DOT2"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW1",
            "name": "ARROW1",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW1"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW2",
            "name": "ARROW2",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW2"
        },                {
            "fqsen": "\\CliForms\\RowHeaderType\u003A\u003AARROW3",
            "name": "ARROW3",
            "summary": "",
            "url": "classes/CliForms-RowHeaderType.html#constant_ARROW3"
        },                {
            "fqsen": "\\Data\\Enum",
            "name": "Enum",
            "summary": "Creating\u0020Enum\u0020objects",
            "url": "classes/Data-Enum.html"
        },                {
            "fqsen": "\\Data\\Enum\u003A\u003AGetValues\u0028\u0029",
            "name": "GetValues",
            "summary": "Get\u0020all\u0020values\u0020of\u0020Enum",
            "url": "classes/Data-Enum.html#method_GetValues"
        },                {
            "fqsen": "\\Data\\Enum\u003A\u003AHasItem\u0028\u0029",
            "name": "HasItem",
            "summary": "",
            "url": "classes/Data-Enum.html#method_HasItem"
        },                {
            "fqsen": "\\Data\\Exceptions\\CreateEnumInstanceException",
            "name": "CreateEnumInstanceException",
            "summary": "",
            "url": "classes/Data-Exceptions-CreateEnumInstanceException.html"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors",
            "name": "BackgroundColors",
            "summary": "Contains\u0020background\u0020color\u0020codes\u0020for\u0020CLI",
            "url": "classes/Data-String-BackgroundColors.html"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AAUTO",
            "name": "AUTO",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_AUTO"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ABLACK",
            "name": "BLACK",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_BLACK"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ARED",
            "name": "RED",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_RED"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AGREEN",
            "name": "GREEN",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_GREEN"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AYELLOW",
            "name": "YELLOW",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_YELLOW"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ABLUE",
            "name": "BLUE",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_BLUE"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003AMAGENTA",
            "name": "MAGENTA",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_MAGENTA"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ACYAN",
            "name": "CYAN",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_CYAN"
        },                {
            "fqsen": "\\Data\\String\\BackgroundColors\u003A\u003ALIGHT_GRAY",
            "name": "LIGHT_GRAY",
            "summary": "",
            "url": "classes/Data-String-BackgroundColors.html#constant_LIGHT_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ColoredString",
            "name": "ColoredString",
            "summary": "Makes\u0020your\u0020string\u0020colored",
            "url": "classes/Data-String-ColoredString.html"
        },                {
            "fqsen": "\\Data\\String\\ColoredString\u003A\u003AGet\u0028\u0029",
            "name": "Get",
            "summary": "",
            "url": "classes/Data-String-ColoredString.html#method_Get"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors",
            "name": "ForegroundColors",
            "summary": "Contains\u0020foreground\u0020color\u0020codes\u0020for\u0020CLI",
            "url": "classes/Data-String-ForegroundColors.html"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AAUTO",
            "name": "AUTO",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_AUTO"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABLACK",
            "name": "BLACK",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BLACK"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_GRAY",
            "name": "DARK_GRAY",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_BLUE",
            "name": "DARK_BLUE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_BLUE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABLUE",
            "name": "BLUE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BLUE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_GREEN",
            "name": "DARK_GREEN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_GREEN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AGREEN",
            "name": "GREEN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_GREEN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_CYAN",
            "name": "DARK_CYAN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_CYAN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ACYAN",
            "name": "CYAN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_CYAN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_RED",
            "name": "DARK_RED",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_RED"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ARED",
            "name": "RED",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_RED"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ADARK_PURPLE",
            "name": "DARK_PURPLE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_DARK_PURPLE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003APURPLE",
            "name": "PURPLE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_PURPLE"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003ABROWN",
            "name": "BROWN",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_BROWN"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AYELLOW",
            "name": "YELLOW",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_YELLOW"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AGRAY",
            "name": "GRAY",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_GRAY"
        },                {
            "fqsen": "\\Data\\String\\ForegroundColors\u003A\u003AWHITE",
            "name": "WHITE",
            "summary": "",
            "url": "classes/Data-String-ForegroundColors.html#constant_WHITE"
        },                {
            "fqsen": "\\IO\\Console",
            "name": "Console",
            "summary": "Console\u0020tools",
            "url": "classes/IO-Console.html"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AReadLine\u0028\u0029",
            "name": "ReadLine",
            "summary": "Reads\u0020line\u0020from\u0020default\u0020stream\u0020input.\u0020Attention\u0021\u0020In\u0020child\u002Dthreads\u0020this\u0020method\u0020works\u0020only\u0020in\u0020Windows\u0020but\u0020doesn\u0027t\u0020work\u0020in\u0020\u002AUnix\u0020systems",
            "url": "classes/IO-Console.html#method_ReadLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AWriteLine\u0028\u0029",
            "name": "WriteLine",
            "summary": "Writes\u0020text\u0020to\u0020default\u0020stream\u0020output\u0020and\u0020sets\u0020pointer\u0020to\u0020new\u0020line",
            "url": "classes/IO-Console.html#method_WriteLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AWrite\u0028\u0029",
            "name": "Write",
            "summary": "Writes\u0020text\u0020to\u0020default\u0020stream\u0020output",
            "url": "classes/IO-Console.html#method_Write"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AClearLine\u0028\u0029",
            "name": "ClearLine",
            "summary": "Clears\u0020a\u0020line",
            "url": "classes/IO-Console.html#method_ClearLine"
        },                {
            "fqsen": "\\IO\\Console\u003A\u003AClearWindow\u0028\u0029",
            "name": "ClearWindow",
            "summary": "Clears\u0020all\u0020output\u0020on\u0020window",
            "url": "classes/IO-Console.html#method_ClearWindow"
        },                {
            "fqsen": "\\IO\\FileDirectory",
            "name": "FileDirectory",
            "summary": "File\u0020system\u0020tools",
            "url": "classes/IO-FileDirectory.html"
        },                {
            "fqsen": "\\IO\\FileDirectory\u003A\u003ACopy\u0028\u0029",
            "name": "Copy",
            "summary": "Copies\u0020file\u0020or\u0020folders\u0020to\u0020target\u0020directory",
            "url": "classes/IO-FileDirectory.html#method_Copy"
        },                {
            "fqsen": "\\IO\\FileDirectory\u003A\u003ADelete\u0028\u0029",
            "name": "Delete",
            "summary": "Deletes\u0020file\u0020or\u0020directory\u0020\u0028even\u0020if\u0020directory\u0020is\u0020not\u0020empty\u0029",
            "url": "classes/IO-FileDirectory.html#method_Delete"
        },                {
            "fqsen": "\\Threading\\ChildThreadedObject",
            "name": "ChildThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020all\u0020methods\u0020and\u0020properties\u0020in\u0020child\u0020threaded\u0020class",
            "url": "classes/Threading-ChildThreadedObject.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\AbstractClassThreadException",
            "name": "AbstractClassThreadException",
            "summary": "",
            "url": "classes/Threading-Exceptions-AbstractClassThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\AccessToClosedThreadException",
            "name": "AccessToClosedThreadException",
            "summary": "",
            "url": "classes/Threading-Exceptions-AccessToClosedThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\BadDataAccessException",
            "name": "BadDataAccessException",
            "summary": "",
            "url": "classes/Threading-Exceptions-BadDataAccessException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\BadMethodCallException",
            "name": "BadMethodCallException",
            "summary": "",
            "url": "classes/Threading-Exceptions-BadMethodCallException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\ClassNotFoundException",
            "name": "ClassNotFoundException",
            "summary": "",
            "url": "classes/Threading-Exceptions-ClassNotFoundException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\InvalidArgumentsPassedException",
            "name": "InvalidArgumentsPassedException",
            "summary": "",
            "url": "classes/Threading-Exceptions-InvalidArgumentsPassedException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\InvalidResultReceivedException",
            "name": "InvalidResultReceivedException",
            "summary": "",
            "url": "classes/Threading-Exceptions-InvalidResultReceivedException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\NewThreadException",
            "name": "NewThreadException",
            "summary": "",
            "url": "classes/Threading-Exceptions-NewThreadException.html"
        },                {
            "fqsen": "\\Threading\\Exceptions\\SystemMethodCallException",
            "name": "SystemMethodCallException",
            "summary": "",
            "url": "classes/Threading-Exceptions-SystemMethodCallException.html"
        },                {
            "fqsen": "\\Threading\\ParentThreadedObject",
            "name": "ParentThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020all\u0020methods\u0020and\u0020properties\u0020in\u0020parent\u0020threaded\u0020object",
            "url": "classes/Threading-ParentThreadedObject.html"
        },                {
            "fqsen": "\\Threading\\Thread",
            "name": "Thread",
            "summary": "Allows\u0020you\u0020to\u0020create\u0020new\u0020threads.\u0020At\u0020the\u0020same\u0020time,\u0020this\u0020class\u0020is\u0020used\u0020by\u0020the\u0020child\u0020thread\u0020to\u0020access\u0020the\u0020parent",
            "url": "classes/Threading-Thread.html"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AThreaded\u0028\u0029",
            "name": "Threaded",
            "summary": "This\u0020method\u0020calls\u0020automatically\u0020in\u0020child\u002Dthread\u0020when\u0020it\u0020was\u0020created",
            "url": "classes/Threading-Thread.html#method_Threaded"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetParentThreadPid\u0028\u0029",
            "name": "GetParentThreadPid",
            "summary": "Returns\u0020a\u0020PID\u0020of\u0020parent\u0020thread",
            "url": "classes/Threading-Thread.html#method_GetParentThreadPid"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AIsParentStillRunning\u0028\u0029",
            "name": "IsParentStillRunning",
            "summary": "Returns\u0020TRUE\u0020if\u0020parent\u0020thread\u0020still\u0020running",
            "url": "classes/Threading-Thread.html#method_IsParentStillRunning"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AIsWindows\u0028\u0029",
            "name": "IsWindows",
            "summary": "",
            "url": "classes/Threading-Thread.html#method_IsWindows"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AGetParentThreadedObject\u0028\u0029",
            "name": "GetParentThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020public\u0020methods\u0020and\u0020properties\u0020of\u0020threaded\u0020parent\u0020object",
            "url": "classes/Threading-Thread.html#method_GetParentThreadedObject"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AWaitForParentAccess\u0028\u0029",
            "name": "WaitForParentAccess",
            "summary": "Blocks\u0020child\u002Dthread\u0020and\u0020waits\u0020when\u0020parent\u002Dthread\u0020will\u0020join\u0020to\u0020child\u002Dthread",
            "url": "classes/Threading-Thread.html#method_WaitForParentAccess"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003AFinishSychnorization\u0028\u0029",
            "name": "FinishSychnorization",
            "summary": "Unjoins\u0020and\u0020unblocks\u0020parent\u002Dthread.\u0020ATTENTION\u0021\u0020Until\u0020you\u0020call\u0020this\u0020method,\u0020the\u0020parent\u002Dthread\u0020will\u0020be\u0020frozen\u0021",
            "url": "classes/Threading-Thread.html#method_FinishSychnorization"
        },                {
            "fqsen": "\\Threading\\Thread\u003A\u003ARun\u0028\u0029",
            "name": "Run",
            "summary": "Creates\u0020and\u0020starts\u0020a\u0020new\u0020thread\u0020of\u0020class",
            "url": "classes/Threading-Thread.html#method_Run"
        },                {
            "fqsen": "\\Threading\\Threaded",
            "name": "Threaded",
            "summary": "Provides\u0020information\u0020and\u0020access\u0020to\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetChildThreadedObject\u0028\u0029",
            "name": "GetChildThreadedObject",
            "summary": "Provides\u0020access\u0020to\u0020public\u0020methods\u0020and\u0020properties\u0020of\u0020threaded\u0020child\u0020class",
            "url": "classes/Threading-Threaded.html#method_GetChildThreadedObject"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetChildPid\u0028\u0029",
            "name": "GetChildPid",
            "summary": "Returns\u0020PID\u0020of\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_GetChildPid"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetArguments\u0028\u0029",
            "name": "GetArguments",
            "summary": "Returns\u0020list\u0020of\u0020arguments\u0020passed\u0020by\u0020the\u0020parent\u0020thread",
            "url": "classes/Threading-Threaded.html#method_GetArguments"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AGetClassName\u0028\u0029",
            "name": "GetClassName",
            "summary": "Returns\u0020name\u0020of\u0020threaded\u0020class",
            "url": "classes/Threading-Threaded.html#method_GetClassName"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AIsRunning\u0028\u0029",
            "name": "IsRunning",
            "summary": "Returns\u0020TRUE\u0020if\u0020child\u0020thread\u0020still\u0020running",
            "url": "classes/Threading-Threaded.html#method_IsRunning"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AWaitForChildAccess\u0028\u0029",
            "name": "WaitForChildAccess",
            "summary": "Waits\u0020for\u0020the\u0020child\u0020thread\u0020to\u0020begin\u0020interacting\u0020with\u0020the\u0020parent\u0020thread.\u0020The\u0020parent\u0020thread\u0020will\u0020be\u0020frozen\u0020and\u0020wait\u0020for\u0020the\u0020child\u0020thread\u0020to\u0020finish\u0020synchronizing",
            "url": "classes/Threading-Threaded.html#method_WaitForChildAccess"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AFinishSychnorization\u0028\u0029",
            "name": "FinishSychnorization",
            "summary": "Stop\u0020synchronization\u0020with\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_FinishSychnorization"
        },                {
            "fqsen": "\\Threading\\Threaded\u003A\u003AKill\u0028\u0029",
            "name": "Kill",
            "summary": "Kills\u0020child\u0020thread",
            "url": "classes/Threading-Threaded.html#method_Kill"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Application",
            "name": "Application",
            "summary": "",
            "url": "namespaces/application.html"
        },                {
            "fqsen": "\\CliForms\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/cliforms-exceptions.html"
        },                {
            "fqsen": "\\CliForms\\ListBox",
            "name": "ListBox",
            "summary": "",
            "url": "namespaces/cliforms-listbox.html"
        },                {
            "fqsen": "\\CliForms\\MenuBox",
            "name": "MenuBox",
            "summary": "",
            "url": "namespaces/cliforms-menubox.html"
        },                {
            "fqsen": "\\CliForms",
            "name": "CliForms",
            "summary": "",
            "url": "namespaces/cliforms.html"
        },                {
            "fqsen": "\\Data",
            "name": "Data",
            "summary": "",
            "url": "namespaces/data.html"
        },                {
            "fqsen": "\\Data\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/data-exceptions.html"
        },                {
            "fqsen": "\\Data\\String",
            "name": "String",
            "summary": "",
            "url": "namespaces/data-string.html"
        },                {
            "fqsen": "\\IO",
            "name": "IO",
            "summary": "",
            "url": "namespaces/io.html"
        },                {
            "fqsen": "\\Threading",
            "name": "Threading",
            "summary": "",
            "url": "namespaces/threading.html"
        },                {
            "fqsen": "\\Threading\\Exceptions",
            "name": "Exceptions",
            "summary": "",
            "url": "namespaces/threading-exceptions.html"
        }            ]
);
